---
- name: "deploy jenkins"
  gather_facts: true
  hosts: all   
  become: yes
  become_user: jenkins-slave2 #sudo: a password is required fix
  become_method: sudo
  roles:
    - docker
    - docker-init
    - elasticsearch
    - kibana
    - logstash
    - heartbeat
    - nginx
    - image-scanner          
  tasks:    
  - name: "OS fingerprinting "
    debug:
      msg:
      - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
      - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
      - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
      - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
      - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"

